### PR TITLE
changed location of data from daily/ to data/ch in the README

### PR DESCRIPTION
**Pull request by karoliskoncevicius**
In preparation of getting rid of the daily/ folder updated README.Rmd to use data/ch instead of daily/

### CODE REVIEW

**Review by pat-s — COMMENTED** [review]
This might break the deployment since we are writing to `daily/` AFAIR. Please check and also adjust this in `trendecon/trendecon`.

**Comment by karoliskoncevicius** [comment]
Thanks for the info. Already sent a pull request to `trendcon/dashboard`. And `trendcon/trendcon/` seems to be still writing to both places (will be adjusted once dashboard is set).

This pull request is only for `README` which, I assume, is not related to deployment?

**Comment by christophsax** [comment]
Feel free to merge uncontroversial stuff without review.

**Comment by pat-s** [comment]
Ah sorry did not see that it was only the README.

**Comment by karoliskoncevicius** [comment]
@pat-s How does Readme.Rmd work in GitHub? I have never encountered it. Do I need to knit it manually and push the updated Readme.md file as well? Or will that be taken care of automatically?

**Comment by pat-s** [comment]
> Do I need to knit it manually and push the updated Readme.md file as well?

yes

**Pull request merged**
